package vouch

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	bootstrap "github.com/duriantaco/vouch/internal/vouch/bootstrap"
)

func TestBootstrapDryRunDraftsConservativeContracts(t *testing.T) {
	repo := bootstrapFixture(t)
	var stdout, stderr bytes.Buffer

	code := Main([]string{"--repo", repo, "bootstrap", "--dry-run"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("bootstrap --dry-run failed: code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}

	out := stdout.String()
	for _, want := range []string{
		"Detected 1 contract drafts:",
		"HIGH auth.password_reset",
		"internal/auth/password_reset.go",
		"test: tests/auth/test_password_reset.py::test_token_expiry",
		"required_test.token_expiry",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("expected dry-run output to contain %q, got:\n%s", want, out)
		}
	}
	if _, err := LoadJSON[bootstrap.Result](filepath.Join(repo, ".vouch", "build", "bootstrap-report.json")); err == nil {
		t.Fatal("dry-run wrote bootstrap report")
	}
	if fileExists(filepath.Join(repo, ".vouch", "intents", "auth.password_reset.yaml")) {
		t.Fatal("dry-run wrote intent file")
	}
}

func TestBootstrapWritesIntentReportAndCompileCompatibleContract(t *testing.T) {
	repo := bootstrapFixture(t)
	var stdout, stderr bytes.Buffer

	code := Main([]string{"--repo", repo, "bootstrap"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("bootstrap failed: code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}

	intentPath := filepath.Join(repo, ".vouch", "intents", "auth.password_reset.yaml")
	reportPath := filepath.Join(repo, ".vouch", "build", "bootstrap-report.json")
	if !fileExists(filepath.Join(repo, ".vouch", "policy", "release-policy.json")) {
		t.Fatal("bootstrap did not initialize the default release policy")
	}
	if !fileExists(intentPath) {
		t.Fatal("bootstrap did not write the generated intent")
	}
	intentText, err := os.ReadFile(intentPath)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"# Generated by vouch bootstrap.",
		"# Review before relying on this contract.",
		"# Vouch used repo signals; it did not infer product intent.",
		"# TODO: replace with the owning team or maintainer.",
		"# TODO: confirm this risk level before enforcing the contract.",
		"# TODO: edit behavior obligations that do not match product intent.",
		"# TODO: confirm security obligations, especially for high-risk components.",
		"# TODO: confirm required tests and map any missing tests before gating.",
		"# TODO: confirm rollback expectations for this component.",
	} {
		if !strings.Contains(string(intentText), want) {
			t.Fatalf("expected generated intent to contain %q, got:\n%s", want, string(intentText))
		}
	}
	report := mustLoadBootstrapReport(t, reportPath)
	if len(report.Drafts) != 1 {
		t.Fatalf("expected one bootstrap draft, got %#v", report.Drafts)
	}
	obligations := report.Drafts[0].Obligations
	if len(obligations) == 0 {
		t.Fatalf("expected generated obligations, got %#v", report.Drafts[0])
	}
	if obligations[0].Generated.By != "vouch.bootstrap" || obligations[0].Generated.Source.File == "" {
		t.Fatalf("expected structured provenance on obligation, got %#v", obligations[0])
	}

	spec, err := CompileIntentFile(intentPath, filepath.Join(repo, ".vouch", "specs", "auth.password_reset.spec.json"))
	if err != nil {
		t.Fatalf("generated intent did not compile: %v", err)
	}
	if spec.ID != "auth.password_reset" || spec.Risk != RiskHigh || spec.Owner != "security-team" {
		t.Fatalf("compiled unexpected spec metadata: %#v", spec)
	}
	if !contains(spec.OwnedPaths, "internal/auth/password_reset.go") {
		t.Fatalf("expected generated spec to preserve source path, got %#v", spec.OwnedPaths)
	}
	if !contains(spec.Tests.Required, "token expiry") {
		t.Fatalf("expected generated spec to preserve required test, got %#v", spec.Tests.Required)
	}
}

func TestBootstrapCheckFailsUntilGeneratedFilesAreCurrent(t *testing.T) {
	repo := bootstrapFixture(t)
	var stdout, stderr bytes.Buffer

	code := Main([]string{"--repo", repo, "bootstrap", "--check"}, &stdout, &stderr)
	if code != 1 {
		t.Fatalf("expected bootstrap --check to fail before files are written: code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}
	if !strings.Contains(stdout.String(), "Bootstrap check failed") {
		t.Fatalf("expected check failure message, got:\n%s", stdout.String())
	}

	stdout.Reset()
	stderr.Reset()
	code = Main([]string{"--repo", repo, "bootstrap"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("bootstrap write failed: code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}

	stdout.Reset()
	stderr.Reset()
	code = Main([]string{"--repo", repo, "bootstrap", "--check"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("expected bootstrap --check to pass after write: code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}
	if strings.Contains(stdout.String(), "Bootstrap check failed") {
		t.Fatalf("unexpected check failure after write:\n%s", stdout.String())
	}
}

func TestBootstrapReviewRanksAndBoundsOutput(t *testing.T) {
	repo := bootstrapReviewFixture(t)
	var stdout, stderr bytes.Buffer

	code := Main([]string{"--repo", repo, "bootstrap", "--review"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("bootstrap --review failed: code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}

	out := stdout.String()
	for _, want := range []string{
		"Recommended contract drafts:",
		"Showing 8 of 10",
		"HIGH auth.session",
		"MED api.users",
		"review: owner, risk",
		"edit: .vouch/intents/auth.session.yaml",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("expected review output to contain %q, got:\n%s", want, out)
		}
	}
	if strings.Contains(out, "LOW docs.readme") {
		t.Fatalf("expected default review output to hide low-priority overflow draft, got:\n%s", out)
	}
	if fileExists(filepath.Join(repo, ".vouch", "intents", "auth.session.yaml")) {
		t.Fatal("bootstrap --review wrote generated intent")
	}
}

func TestBootstrapReviewLimitAllAndJSON(t *testing.T) {
	repo := bootstrapReviewFixture(t)
	var stdout, stderr bytes.Buffer

	code := Main([]string{"--repo", repo, "bootstrap", "--review", "--limit", "2"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("bootstrap --review --limit failed: code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}
	if !strings.Contains(stdout.String(), "Showing 2 of 10") || strings.Contains(stdout.String(), "MED api.users") {
		t.Fatalf("expected --limit 2 to show only top high-risk drafts, got:\n%s", stdout.String())
	}

	stdout.Reset()
	stderr.Reset()
	code = Main([]string{"--repo", repo, "bootstrap", "--review", "--all"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("bootstrap --review --all failed: code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}
	if !strings.Contains(stdout.String(), "LOW docs.readme") || strings.Contains(stdout.String(), "Showing 8 of 10") {
		t.Fatalf("expected --all to show every draft without bounded message, got:\n%s", stdout.String())
	}

	stdout.Reset()
	stderr.Reset()
	code = Main([]string{"--repo", repo, "--json", "bootstrap", "--review", "--limit", "3"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("bootstrap --review --json failed: code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}
	var review bootstrap.ReviewResult
	if err := json.Unmarshal(stdout.Bytes(), &review); err != nil {
		t.Fatalf("review JSON is invalid: %v\n%s", err, stdout.String())
	}
	if review.Version != bootstrap.ReviewVersion || review.TotalDrafts != 10 || review.DisplayedDrafts != 3 {
		t.Fatalf("unexpected review JSON: %#v", review)
	}
	if len(review.Drafts) == 0 || review.Drafts[0].Risk != "high" {
		t.Fatalf("expected high-risk draft first in review JSON, got %#v", review.Drafts)
	}
}

func bootstrapFixture(t *testing.T) string {
	t.Helper()
	repo := t.TempDir()
	writeText(t, filepath.Join(repo, "pyproject.toml"), `[tool.pytest.ini_options]
testpaths = ["tests"]
`)
	writeText(t, filepath.Join(repo, "CODEOWNERS"), `/internal/auth/** @security-team
/tests/auth/** @security-team
`)
	writeText(t, filepath.Join(repo, "internal", "auth", "password_reset.go"), `package auth

func ResetPassword() {}
`)
	writeText(t, filepath.Join(repo, "tests", "auth", "test_password_reset.py"), `def test_token_expiry():
    assert True
`)
	writeText(t, filepath.Join(repo, ".github", "workflows", "ci.yml"), `name: CI
`)
	return repo
}

func bootstrapReviewFixture(t *testing.T) string {
	t.Helper()
	repo := t.TempDir()
	writeText(t, filepath.Join(repo, "pyproject.toml"), `[tool.pytest.ini_options]
testpaths = ["tests"]
`)
	cases := []struct {
		path string
		body string
	}{
		{"tests/admin/test_role.py", "def test_role_contract():\n    assert True\n"},
		{"tests/api/test_users.py", "def test_users_contract():\n    assert True\n"},
		{"tests/auth/test_session.py", "def test_session_contract():\n    assert True\n"},
		{"tests/billing/test_invoice.py", "def test_invoice_contract():\n    assert True\n"},
		{"tests/db/test_schema.py", "def test_schema_contract():\n    assert True\n"},
		{"tests/docs/test_readme.py", "def test_readme_contract():\n    assert True\n"},
		{"tests/payments/test_checkout.py", "def test_checkout_contract():\n    assert True\n"},
		{"tests/routes/test_handler.py", "def test_handler_contract():\n    assert True\n"},
		{"tests/secrets/test_key.py", "def test_key_contract():\n    assert True\n"},
		{"tests/static/test_css.py", "def test_css_contract():\n    assert True\n"},
	}
	for _, tc := range cases {
		writeText(t, filepath.Join(repo, tc.path), tc.body)
	}
	return repo
}

func mustLoadBootstrapReport(t *testing.T, path string) bootstrap.Result {
	t.Helper()
	report, err := LoadJSON[bootstrap.Result](path)
	if err != nil {
		t.Fatal(err)
	}
	return report
}
